# Generated by Django 5.1.3 on 2024-12-03 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0002_alter_room_options_remove_room_date_remove_room_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomparticipant',
            name='joined_at',
        ),
    ]
