# Generated by Django 5.1.2 on 2024-11-25 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_parties', to='users.user')),
            ],
            options={
                'verbose_name': 'Scheduled Party',
                'verbose_name_plural': 'Scheduled Parties',
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='users.user')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_users', to='calender.scheduledparty')),
            ],
            options={
                'verbose_name': 'Party Invite',
                'verbose_name_plural': 'Party Invites',
                'unique_together': {('user', 'party')},
            },
        ),
    ]
