# Generated by Django 5.1.1 on 2024-12-02 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0001_initial'),
        ('users', '0002_voicemessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='users.user'),
        ),
        migrations.AlterField(
            model_name='scheduledparty',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_parties', to='users.user'),
        ),
    ]
