# Generated by Django 5.1.3 on 2024-11-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('playlist_name', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('username', 'playlist_name')},
            },
        ),
    ]
