# Generated by Django 5.1.3 on 2024-11-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='playlistdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=255)),
                ('playlist_name', models.CharField(max_length=100)),
                ('name', models.CharField(default='default_name', max_length=255, unique=True)),
            ],
        ),
    ]
