# Generated by Django 5.1.3 on 2024-11-30 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('host', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Private'), (2, 'Public')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
            ],
            options={
                'verbose_name': 'Scheduled Party',
                'verbose_name_plural': 'Scheduled Parties',
            },
        ),
    ]
